---
apiVersion: v1
data:
  cluster.name: appmesh
  logs.region: us-east-1
  # The below configuration file is in JSON format.
  # Please ensure you keep it well-formed if you modify it.
  cluster-info.json: |
    {
      "cluster": {
        "name": "appmesh"
      },
      "logs": {
        "region": "us-east-1"
      }
    }
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: amazon-cloudwatch
